### ISSUE TITLE
Progress bar and circle do not move

### ISSUE THREAD

**Issue by zdrsoft** [react-component/progress#11]
Hi,
The component looks great, but I have an issue with usage of it. Please, help me. I have imported rc-progress it in the project. For example I use it on the first page in react application, the progress indicator Circle is shown in grey color, but no movement is visible in the circle. 

`import { Circle } from 'rc-progress';`
..........
in render method:
```
<div className="progressInd">
    <Circle percent="10" strokeWidth="4" strokeColor="#D3D3D3" />
</div>
```

Here is the HTML code produced by the Circle component in the browser page source:

<svg class="rc-progress-circle " viewBox="0 0 100 100"><path class="rc-progress-circle-trail" d="M 50,50 m 0,-48
     a 48,48 0 1 1 0,96
     a 48,48 0 1 1 0,-96" stroke="#D9D9D9" stroke-width="1" fill-opacity="0"></path><path class="rc-progress-circle-path" d="M 50,50 m 0,-48
     a 48,48 0 1 1 0,96
     a 48,48 0 1 1 0,-96" stroke-linecap="round" stroke="#D3D3D3" stroke-width="4" fill-opacity="0" style="stroke-dasharray: 301.593px, 301.593px; stroke-dashoffset: 271.434px; transition: stroke-dashoffset 0s ease 0s, stroke 0s ease;"></path></svg>

here is what is rendered in the browser:
![pi_issue](https://cloud.githubusercontent.com/assets/712462/20343216/325456c0-abf6-11e6-90ad-b433ae02d112.png)

What could be the problem with the progress indicator?

**Comment by afc163** [comment]
It is a progress, not a progress indicator.

Check: http://react-component.github.io/progress/examples/fast-progress.html

**Comment by zdrsoft** [comment]
Thank you.
