### ISSUE TITLE
strokeLinecap default should be 'butt'

### ISSUE THREAD

**Issue by codemonkeynorth** [react-component/progress#14]
'butt' is the default, but your default is 'round' and 'butt' is excluded from the options

see:
https://css-tricks.com/almanac/properties/s/stroke-linecap/

therefore
https://github.com/react-component/progress/blob/2.0.3/src/mixin.js#L10
should presumably be eg
`strokeLinecap: PropTypes.oneOf(['butt', 'round', 'square']),`

and
https://github.com/react-component/progress/blob/2.0.3/src/mixin.js#L21
should be 
`strokeLinecap: 'butt',`

thanks

**Comment by pencilcheck** [comment]
I'm getting warning about butt is not a valid option. It should be!

**Comment by pencilcheck** [comment]
It would be nice if this is released in a new version. Appreciated for the quick turnaround for this issue.

**Comment by paranoidjk** [comment]
@afc163 
```bash
npm owner ls rc-progress                                         
afc163 <afc163@gmail.com>
tsj1107 <tsjxyz@gmail.com>
yiminghe <yiminghe@gmail.com>
```

**Comment by afc163** [comment]
done

**Comment by paranoidjk** [comment]
@pencilcheck 2.1.2
