### ISSUE TITLE
Firefox bug

### ISSUE THREAD

**Issue by brezhitskiy42** [react-component/progress#15]
In firefox, when circle percent 0 - stroke width it is still visible.

**Comment by pszpaidel** [comment]
In IE 11, the same issue.

**Comment by paranoidjk** [comment]
can you give the specifica version？

**Comment by pszpaidel** [comment]
![ie](https://cloud.githubusercontent.com/assets/22989946/26497129/8f697910-422a-11e7-937a-9bc74ffa776d.png)

**Comment by benjycui** [comment]
It can be re-produced in Chrome:

![image](https://user-images.githubusercontent.com/3580607/27521876-f0959ac0-5a53-11e7-96b0-c9494b349874.png)
