### ISSUE TITLE
version 2.0.5 bug in mixin.js

### ISSUE THREAD

**Issue by wuzeru** [react-component/progress#17]
![image](https://cloud.githubusercontent.com/assets/6448232/21761380/845168f2-d68d-11e6-99cc-017bd28aa9e3.png)
it should be `this.refs.path`? `this.path` is undefined

**Comment by afc163** [comment]
https://github.com/react-component/progress/pull/12

Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by wuzeru** [comment]
http://codepen.io/wuzeru/pen/WRQpwY 这里没有报出错误，是rc-progress版本不一样？

**Comment by wuzeru** [comment]
![image](https://cloud.githubusercontent.com/assets/6448232/21763564/6f966424-d699-11e6-9839-5baf06c4fe34.png)
Circle.js 是不是漏处理这里的ref了？

**Comment by afc163** [comment]
确实，感谢反馈，fixed in 2.0.6
