### ISSUE TITLE
Great! Now how do we stop it from scaling too large?

### ISSUE THREAD

**Issue by kevinbmccall14** [react-component/progress#18]
Thank you for making this great little component. I am looking for away to prevent the `strokeWidth` from scaling too large.

I attempted applying `vector-effect="non-scaling-stroke"` to the React created Paths but it appears to interfere with the pathStyle of the SVG element thus breaking the progress part of the ProgressBar.

Any ideas?

**Comment by JcBernack** [comment]
I managed to prevent the stroke width from scaling using css:

    <Line
      percent={50}
      style={{
        width: '100%',
        height: '10px',
      }}
    />
