### ISSUE TITLE
Circular progress bar does not fill using MS Edge

### ISSUE THREAD

**Issue by ElsewhereGames** [react-component/progress#2]
If you check the demo using MS Edge, you will see that pressing the button will change the color of the progress path, but not how much of the track is filled.

http://react-component.github.io/progress/examples/simple.html

**Comment by benjycui** [comment]
We have not MS Edge... Could you just record a GIF?

**Comment by paranoidjk** [comment]
Test on IE 11

![ie11](https://gw.alipayobjects.com/zos/rmsportal/OmRxtdKGaJKCvfHkqKKu.gif)

**Comment by benjycui** [comment]
@paranoidjk I think it works fine in IE11..

**Comment by wlingke** [comment]
Is this a legit bug? Has anyone tried this in edge?

**Comment by halkeye** [comment]
Seems to work fine in edge 15, not sure how old this bug is.

https://saucelabs.com/beta/tests/ce39988a71614662abba8cfe510bd61e/watch
