### ISSUE TITLE
Circle no longer animates

### ISSUE THREAD

**Issue by dsteinbach** [react-component/progress#21]
When the value of percent changes from 0 to 100 it no longer animates when before it did:
```
<Circle percent={percent} strokeWidth="8" strokeColor="#fff" trailWidth="8" trailColor="#6b6767" />
```

**Comment by afc163** [comment]
![1](https://cloud.githubusercontent.com/assets/507615/24574990/cbf4fe6e-16cd-11e7-9ccb-ebaf3ddcca0f.gif)

**Comment by paranoidjk** [comment]
close for no response.

**Comment by mihaiblaga89** [comment]
I can confirm this, the circle is not animating. Also, the .css and .less files from assets folder are empty.

**Comment by paranoidjk** [comment]
> Also, the .css and .less files from assets folder are empty.

@mihaiblaga89 Because there do no need for stylesheet. see https://github.com/react-component/progress#usage

> the circle is not animating.

Please provide a reproducible demo.
