### ISSUE TITLE
React PropTypes and CreateClass are deprecated

### ISSUE THREAD

**Issue by wemyss** [react-component/progress#22]
As of React 15.5 these are being moved to seperate modules.

I'm happy to create a PR to fix this, though do we want to use ES6 with Babel, or just use the seperate modules?

**Comment by afc163** [comment]
`use ES6 with Babel` would be better.

**Comment by benjycui** [comment]
How about a PR @wemyss

**Comment by wemyss** [comment]
@benjycui starting work on this tomorrow 😸

**Comment by wemyss** [comment]
Thoughts on using flow over proptypes?

**Comment by afc163** [comment]
Consider that people maybe not need TypeScript.

**Comment by benjycui** [comment]
No, just follow the convention, thanks.

**Comment by wemyss** [comment]
That's what I did. I've made majority of the changes on my fork @ https://github.com/wemyss/progress but I have a few questions:

- In the current project we use some es6 features without transpiling it into a production build, should we be doing that in the future?
- Mixins are no longer supported/recommended so I moved away from that, and was unsure whether it was necessary to use a HOC called `Shape` or something to reduce code duplication or just have the `componentDidUpdate` method in both `Line` and `Circle`.
- `rc-tools` complains about `prop-types` not being a dependency of the project when running the linter. Is there a way around this other than making it a dependency rather than a devDependency

**Comment by benjycui** [comment]
> In the current project we use some es6 features without transpiling it into a production build, should we be doing that in the future?

Actually, when we run [`npm run pub`](https://github.com/react-component/progress/blob/master/package.json#L33), it will compile ES6 to ES5.

> Mixins are no longer supported/recommended so I moved away from that, and was unsure whether it was necessary to use a HOC called Shape or something to reduce code duplication or just have the componentDidUpdate method in both Line and Circle.

How about an Inheritance Inversion HOC?

> rc-tools complains about prop-types not being a dependency of the project when running the linter. Is there a way around this other than making it a dependency rather than a devDependency

`prop-types` should be dependencies, for rc-process supports `React@<=15.4`, and developers should not know `prop-types` if they use `React@<=15.4`

**Comment by benjycui** [comment]
@wemyss bravo 👍
