### ISSUE TITLE
Initial Animation

### ISSUE THREAD

**Issue by flamencoflsh** [react-component/progress#28]
I am currently using the Line Progress.  It displays, but does not animate.  Is there something I have to set explicitly for the initial animation to happen?

Thx. 

@afc163 @tsj1107 @yiminghe @pencilcheck @wemyss

**Comment by wemyss** [comment]
you can use the `initialAnimate` prop

**Comment by flamencoflsh** [comment]
@wemyss Do you mean like this?

       <Line percent={60.5} strokeWidth="4" strokeColor="#3e98c7" initialAnimate={true} />

This is still not animating...

**Comment by flamencoflsh** [comment]
@wemyss I saw your other example and tried to use just:

     <Circle percent="60.2" strokeWidth="5" strokeColor="#3e98c7" initialAnimate/>
                       </div>

and

   <Line percent={subGoal.percentage} strokeWidth="4" strokeColor="#3e98c7" initialAnimate />

But there is still no animation.  Do you have any other suggestions of things to try?

Thanks!

@afc163 @tsj1107 @yiminghe @pencilcheck

**Comment by paranoidjk** [comment]
- there is not a `initialAnimate` api, please see the api doc https://github.com/react-component/progress#api
- If you want custom animate, just use css animation.
