### ISSUE TITLE
Text in the Circle

### ISSUE THREAD

**Issue by flamencoflsh** [react-component/progress#29]
Is there a way to display text (such as percentage value, etc.) in the center of the circular progress?

Thx. 

@afc163 @tsj1107 @yiminghe @pencilcheck @wemyss

**Comment by wemyss** [comment]
When I needed this I've used a simple wrapper and absolute position child (I generally always end up looking back to this [https://css-tricks.com/centering-css-complete-guide/](https://css-tricks.com/centering-css-complete-guide/)):

```
// textInCircle.js
<article>
  <div className='progress-wrapper'>
    <span className='progress-title' >TEXT</span>
      <Circle
        progress={value}
        options={options}
        initialAnimate
      />
  </div>
</article>

// textInCircle.css
.progress-title {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.progress-wrapper {
	width: 150px;
	height: 150px;
	margin: auto;
	position: relative;
}
```

**Comment by flamencoflsh** [comment]
Thanks, @wemyss !  Now, I just need to get it to animate.  Closing this, and keeping that issue open =)
