### ISSUE TITLE
CSS for Initial Animation

### ISSUE THREAD

**Issue by flamencoflsh** [react-component/progress#30]
>>paranoidjk commented 27 minutes ago

there is not a initialAnimate api, please see the api doc https://github.com/react-component/progress#api
If you want custom animate, just use css animation.

@paranoidjk, can you expand on what you mean by CSS animation?  I am just looking for that initial animation when the progress bar goes from 0 to whatever the specified percentage is.  Can you give me an example for the syntax?  How would you add that initial animation to something like:

       <Circle percent="60.2" strokeWidth="5" strokeColor="#4b82b0" />

?

Thanks!

@afc163 @tsj1107 @yiminghe @pencilcheck @wemyss

**Comment by benjycui** [comment]
You should learn how to use GItHub first.

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by flamencoflsh** [comment]
@benjycui, I'm not sure what to do with your response. If you don't like my question and want to say why, feel free...

Either way, I'm still looking for the answer to my original question. 

Thanks all.

**Comment by flamencoflsh** [comment]
I figured out that I need to use some kind of increase function to set the progress.  Thanks, all!
