### ISSUE TITLE
Bar at 50% doesn't look like 50%.

### ISSUE THREAD

**Issue by PAK90** [react-component/progress#32]
![image](https://cloud.githubusercontent.com/assets/1844422/26028864/a0331b38-37e5-11e7-982d-8f40a2834271.png)

As you can see, a bar with these settings `<Line percent={votePercent} strokeColor={styles.leftColour} trailColor={styles.rightColour} strokeWidth="5"/>` where `votePercent` is 50 doesn't look at all like it's halfway. The two boxes above are both 100px wide and at equal distance from each other and the line. This is a bit weird, to be honest.

**Comment by benjycui** [comment]
I think you need to override `border-radius`.
