### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by sheam** [react-component/progress#37]
Anyone get this working with Typescript? Please share your .d.ts.

**Comment by benjycui** [comment]
And PR is welcomed.

**Comment by TizioFittizio** [comment]
I write the .d.ts. file for this plugin and its seems to work, however i would like to use a compiled es5 version of the sources since es6 libraries are incompatible with react-create-app
Which files i have to edit/add in order to use a compiled version?

**Comment by Jagatmachines** [comment]
@TizioFittizio could u share ur .d.ts file for the library with us. Thank u in advance

**Comment by benesch** [comment]
Here's something we're using at CockroachDB that could get you started:
https://github.com/cockroachdb/cockroach/blob/faa1d2b46708f4f84cd552af6dc7258373fdebb0/pkg/ui/src/hacks/rc-progress.d.ts
