### ISSUE TITLE
状态和进度不同步

### ISSUE THREAD

**Issue by wuzhao** [react-component/progress#4]
先显示状态再变跟进度，如果变化区间较大时感觉到唐突，如下图：

![3](https://cloud.githubusercontent.com/assets/712075/12029237/cbcca1e2-ae20-11e5-9135-24bd3a694196.gif)

**Comment by benjycui** [comment]
现在还没有相对完善的破解方式，see：https://github.com/facebook/react/issues/2187

**Comment by afc163** [comment]
看样子是先设置了 `status="success"` 再 设置了 `percent={100}`。

业务上需要保持同步设置，一般只需设置 `percent` 就好。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/develop-0.12.0/components/progress/index.jsx#L124

其实 `Progress.Circle` 会自行更新状态的。所以出现这种现象是原因是因为，进度已经 100% 了，所以 `Progress.Circle` 自行设置状态为 success，同时设置 `stroke-dashoffset`，但因为样式的 `transition` 设置了 delay，所以状态在动画执行完之前就已经切换了。
