### ISSUE TITLE
How do you get just a smooth circular animation from 0 to 100?

### ISSUE THREAD

**Issue by jwmann** [react-component/progress#42]
I tried to do this in two ways.
First way was to set it from 0 to 100 and then just change the speed of the transition. Except that didn't seem to work at all for me. Though I feel like this should achieve the best results since the transitions are smoother than a state update.

The second way was to make a state update loop to bring it from 0 to 100.
I'm doing this the way @matthlavacka is showing in #5 

The problem is that it's not very smooth and it seems to have the issue of not updating the circular bar progress until it's at like 45%, not very smooth.

https://jwm.d.pr/xVGSJJ/iR4iQJnY5N
![GIF](https://user-images.githubusercontent.com/436270/38815957-0a93a4c0-4163-11e8-80a4-0f7aa5dd9ce2.gif)

Here's a somewhat choppy gif showing what I mean. You can see that the numbers start updating before the bar does.

The reset button, aka, setting the state to 0, has a really smooth animation. When I try this with 100 it just glitches for .3 seconds and then appears green. 
There must be a better way D:

**Comment by coolstuff-michael** [comment]
This is probably fixed with https://github.com/react-component/progress/pull/80

**Comment by mjfwebb** [comment]
This is probably fixed by https://github.com/react-component/progress/issues/42
