### ISSUE TITLE
IE 11 look weird

### ISSUE THREAD

**Issue by chaoriwei** [react-component/progress#49]
![image 1](https://user-images.githubusercontent.com/16182457/41027993-023baf50-69ab-11e8-85e6-314767342a2b.png)

**Comment by tuanzhang7** [comment]
same here, please help to solve it

**Comment by Bosch-Eli-Black** [comment]
This appears to be due to the `preserveAspectRatio="none meet"` attribute that's on the `.rc-progress-line` svg element.

Removing this attribute fixes the issue in IE 11.

As a workaround, one can add an explicit height to the `.rc-progress-line` element, like so:

```
.rc-progress-line {
   height: 11px;
}
```

**Comment by tpkemme** [comment]
@Bosch-Eli-Black Removing preserveAspectRatio="none meet" does not fix this issue for me.  Also, adding an explicit height kind of works, except for when you have the progress bar at 0 percent it still shows an indication of progress.

It's irritating that this project says it supports "IE9+" when clearly it is not working correctly in IE11

**Comment by maxchernin** [comment]
This is a known issue with this lib on I.E.
im experiencing it as-well
