### ISSUE TITLE
Great, but needs control of speed

### ISSUE THREAD

**Issue by matthlavacka** [react-component/progress#5]
Thanks for making this, I wish there was control of speed though.

**Comment by mhlavacka** [comment]
To control speed one can do the following:
```javascript
addPercent() {
  const self = this;
  this.setState({
    percent: this.state.percent + 1,
  });
  setTimeout(function(){ self.changeState(); }, 100);
}

changeState() {
  this.state.percent <= 99 ? this.addPercent() : this.setState({percent: 100});
}
```

**Comment by ajayk800** [comment]
```

return a div element

set that div className="someExampleName"

control from css

.someExampleName {
animation: speed-control linear 0.9s;                  // specify seconds for speed control
}
or use CSS animations? @mhlavacka 

@keyframes speed-control {
0% { height/width/: Whatever }
50%{  height/width: increment }
100%{ height/width: to final position }

// OR //

from { }
to { } 
}
```

**Comment by jwmann** [comment]
@ajayk800 Can you give a more complete example? In theory this can work for a css animation in general but this uses stroke-dasharray values and transitions. I don't think it's that simple.

**Comment by salatielq** [comment]
I did with one CSS line:

`.rc-progress-circle-path {
  transition: stroke-dashoffset 0.9s ease 0s, stroke-dasharray 0.9s ease 0s, stroke 0.9s ease 0s,
    stroke-width 0.1s ease 0.9s !important;
}`

**Comment by xrkffgg** [comment]
You can custom `transition`
https://github.com/react-component/progress/blob/e4a262b1a44b915a1691e859f0c070eeeaac3c29/src/interface.ts#L15
