### ISSUE TITLE
strokeWidth is breaking the progress accuracy

### ISSUE THREAD

**Issue by florian-bd** [react-component/progress#50]
When defining a strokeWidth, the rounded corners are added to the length of the progress, so it looks bad.
You can try with a value of like 10, then it's obvious

![image](https://user-images.githubusercontent.com/11945259/41661770-b6b1af62-749f-11e8-99da-c62dbf41ec7f.png)
![image](https://user-images.githubusercontent.com/11945259/41661821-cfdf1be6-749f-11e8-9c75-ecc196cffb3f.png)

**Comment by josephpung** [comment]
facing similar issue, is there any fix in the pipelines for this issue @benjycui ?

**Comment by xrkffgg** [comment]
Duplication of https://github.com/react-component/progress/issues/90
