### ISSUE TITLE
Progress bar types

### ISSUE THREAD

**Issue by meymeynard** [react-component/progress#52]
## Just a Question

Is there like a style for progress bar such as getting it `striped` like in the Bootstrap (https://getbootstrap.com/docs/4.1/components/progress/#striped)

or does the `prefixCls` allow a custom style for the progress bar?

Thanks!

## Preview
<img width="227" alt="screen shot 2018-10-26 at 5 34 35 pm" src="https://user-images.githubusercontent.com/1303230/47558344-76913a00-d945-11e8-80e2-2e80441f3e05.png">

**Comment by xrkffgg** [comment]
You can use `className` and `style` or https://ant.design/components/progress/
