### ISSUE TITLE
Fast-progress decrease

### ISSUE THREAD

**Issue by FLYERok** [react-component/progress#61]
Hello!
I'm using fast-progress with function to set timeout for decrease:
`decrease = () => {`
`const percent = this.state.percentage - 1;`
`if (percent < 0) {`
`clearTimeout(this.tm);`
`return;`
` }`
`this.setState({ percentage: percent });`
 `this.tm = setTimeout(this.decrease, 30);`
`}`

All is ok. But, when «percent == 0» I see a short delay indicator. After some time it disappears. There is no smoothness. https://codesandbox.io/s/3x6p0w149m

Can you help me, please?

I’m sorry for my English. Thank you very much!

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/progress/pull/80
