### ISSUE TITLE
core-js version

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [react-component/progress#79]
Hello,

When installing rc-progress via yarn, I'm seeing the following error:

> warning rc-progress > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

Could you please update this package's version of Babel? (Or release an updated version of this package on NPM, if Babel has already been updated in master?)

**Comment by xrkffgg** [comment]
update in https://github.com/react-component/progress/pull/85
