### ISSUE TITLE
Requirement - Start point option

### ISSUE THREAD

**Issue by BalavigneshJ** [react-component/progress#81]
Hi, Thanks for the nice component. I need an extra option in the Line progress bar like "start and end" points. This progress bar always starts at 0. I need to option set like start from 20 to 55.
Thanks again.

**Comment by xrkffgg** [comment]
you can use `percent={[]}`  `strokeColor={[]}`

like 
https://github.com/react-component/progress/blob/e4a262b1a44b915a1691e859f0c070eeeaac3c29/examples/simple.tsx#L38-L41
