### ISSUE TITLE
Using useMemo - Disaster for React 15.x

### ISSUE THREAD

**Issue by kapunchan** [react-component/progress#82]
Refactoring progress with hooks seems like a breaking change. Was it appropriate to change version as 2.6.0? Application using React 15.x just crashed after installing new version of progress.

**Comment by kapunchan** [comment]
Using "rc-progress" as ^2.5.3.

**Comment by afc163** [comment]
I published `rc-progress@2.6.1` for react 15 compatibility.

**Comment by kapunchan** [comment]
Bravo! What a quick response! 👏👏👏
