### ISSUE TITLE
missing rc-progress/assets/index.css

### ISSUE THREAD

**Issue by auguszou** [react-component/progress#86]
platform: codesandbox

react: 16.13.1
rc-progress: 3.1.0

please take a look at demo repo
https://codesandbox.io/s/rc-progress-demo-7zp6t?file=/src/App.js

but works in rc-progress: 2.6.1

![image](https://user-images.githubusercontent.com/3761283/92316735-c4d7ef80-f02a-11ea-9dc3-607376bd47cc.png)

**Comment by xrkffgg** [comment]
I found that is empty, so I removed it.

**Comment by xrkffgg** [comment]
You can just remove it.
